### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by demir-delic** [chingu-voyages/v29-bears-team-07#11]
**__Feature Description__**
The client side of the application. Handles user interaction and displays data from the backend.

**__Major User Stories/tasks__**
- [x] Create basic frontend project structure
- [x] Detect a user's location
- [x] Suggest the nearest city supported by Teleport and select it by default
- [x] Allow the user to change their city
- [x] Allow the user to select their preferences and search for recommended cities
- [x] Display recommended cities using data from backend
- [ ] Add autocomplete textfield component

**__Additional Considerations__**
Wireframe: https://drive.google.com/drive/folders/1XKymuXnVBwgESYGmovMTgGDThZPQL-dS
