### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by demir-delic** [chingu-voyages/v29-bears-team-07#12]
**__Feature Description__**
REST API that connects to PostgreSQL database and serves the frontend.

**__Major User Stories/tasks__**
- [x] Clean up CSV data file so that it's ready to be transformed into a database
- [x] Create a PostgreSQL database based on the CSV file
- [x] Research Flask vs. Django and decide which to use for the API
- [x] Start building API - to split into further stories
