### ISSUE TITLE
👍 Choose a project & create a Vision Statement

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v29-bears-team-07#6]
**__Task Description__**
- [x] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)
- [x] Collect ideas from the team
- [x] Brainstorm with your team
- [x] Vote to select one idea
- [x] Decide on the technical stack you’ll use to build your project

**__Technical Considerations__**
N/a

**__Additional Considerations__**
Use the [Project Vision and Feature Planning template](https://docs.google.com/document/d/1pG-6ihL47P6IpMtcgVeb5_DWoatZcsMTwx_lGDmfh9o/edit?usp=sharing) to gather & vote on everyone's idea
