### ISSUE TITLE
⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v29-bears-team-07#9]
**__Task Description__**
- [x] Decide on the coding standards the team must follow.
- [x] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [x] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [x] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [x] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Develop the App](https://docs.google.com/document/d/10erbB9vJbPfRXOad5hPkUv27iqlVGnj1etRu-9QtTjs/edit#heading=h.csvhpxknom3k) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://docs.chingu.io/voyage/project/workflow)
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://docs.chingu.io/techres/gitworkflow)
[Git Branches (Chingu Handbook)](https://docs.chingu.io/techres/gitbranches)
[Git Commits (Chingu Handbook)](https://docs.chingu.io/techres/gitcommits)
[Git Pull Requests (Chingu Handbook)](https://docs.chingu.io/techres/gitprs)

**Comment by demir-delic** [comment]
@xarrijorge @che-vee Here are my suggestions for the standards. Let's discuss in Discord or at our next meeting:

> Decide on the coding standards the team must follow.
- Use a linter and formatter for both frontend and backend
  - ESLint (create-react-app defaults) and Prettier for JavaScript, Pylint/Flake8 and Black for Python

> Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- Workflow recommended by Chingu: https://docs.chingu.io/techres/gitworkflow#git-branches
  - Use one feature branch per story, branch feature branches off of `develop`, merge back to `develop` after peer review of a pull request. `master` is automatically deployed to production, and only `develop` should be merged to `master`.
  - There are 4 basic types of branches: bug, feature, refactor, and style. For example: feature/course-review.

> Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- For commit messages, use the [Conventional Commits standard](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary). Possible commit types: https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum
  - automation optional for now
- PRs should be reviewed by at least one other developer before being merged. Here's one useful guide on how to author and review PRs: https://google.github.io/eng-practices/review/
- `master` branch should be protected (can't push to it directly, only merge other branches into it)

> Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- I suggest deploying on Digital Ocean's app platform while we only have a frontend (I've already set this up); once we have a database and backend that can talk to the frontend, we can switch to Heroku. Latest `master` branch is always deployed to production.

> Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to Develop the App to learn more about the types of meetings you’ll need.
- One meeting per week to do a retro and sprint planning; regular text updates in the Discord channel; pair programming as needed during each sprint.
